# SPDX-FileCopyrightText: 2026 Netbeheer Nederland
# SPDX-License-Identifier: Apache-2.0
"""The TLS certificate directory, as the HMI's TLS dialog lists it.

docker-compose.yml mounts testing/certs (generated by its generate.sh) at
/certs in the BFF and in every RTI-SO / RTI-FSP. The HMI lets a user pick a
file from this listing; the TLS settings then hold the reference
`file:<name>`, which each service resolves against its own mount when it
builds a TLS context (ws61850.security.tls.resolve_pem). Key contents never
leave the directory: a private key is only recognised by its first line here,
never read further.
"""

from __future__ import annotations

import os
from pathlib import Path

from cryptography import x509
from cryptography.x509.oid import NameOID

# Same as ws61850.security.tls, which resolves the references in the RTI-SO /
# RTI-FSP; the BFF only lists the files and doesn't depend on ws61850.
FILE_REF_PREFIX = "file:"
DEFAULT_CERT_DIR = "/certs"

PEM_SUFFIXES = (".pem", ".crt", ".cer", ".key")


def cert_dir() -> Path:
    """The certificate directory: TLS_CERT_DIR, else /certs."""
    return Path(os.environ.get("TLS_CERT_DIR") or DEFAULT_CERT_DIR)


def _first_line(path: Path) -> str:
    with path.open(encoding="utf-8", errors="replace") as f:
        return f.readline(200).strip()


def _common_name(name: x509.Name) -> str | None:
    attrs = name.get_attributes_for_oid(NameOID.COMMON_NAME)
    return attrs[0].value if attrs else None


def _describe_certificate(path: Path) -> dict:
    cert = x509.load_pem_x509_certificate(path.read_bytes())
    try:
        san = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName).value
        sans = [str(v) for v in san.get_values_for_type(x509.DNSName)] + [
            str(v) for v in san.get_values_for_type(x509.IPAddress)
        ]
    except x509.ExtensionNotFound:
        sans = []
    try:
        is_ca = cert.extensions.get_extension_for_class(x509.BasicConstraints).value.ca
    except x509.ExtensionNotFound:
        is_ca = False
    return {
        "kind": "certificate",
        "subject": _common_name(cert.subject) or cert.subject.rfc4514_string(),
        "issuer": _common_name(cert.issuer) or cert.issuer.rfc4514_string(),
        "sans": sans,
        "is_ca": is_ca,
        "not_after": cert.not_valid_after_utc.isoformat(),
    }


def describe(path: Path) -> dict:
    """What one file in the directory is - without returning any key material."""
    try:
        first = _first_line(path)
    except OSError as exc:
        return {"kind": "unreadable", "error": exc.strerror or str(exc)}
    if first.startswith("-----BEGIN") and "PRIVATE KEY" in first:
        return {"kind": "private_key"}
    if first == "-----BEGIN CERTIFICATE-----":
        try:
            return _describe_certificate(path)
        except (ValueError, OSError) as exc:
            return {"kind": "unreadable", "error": str(exc)}
    return {"kind": "other"}


def list_certificates(directory: Path | None = None) -> dict:
    """Every PEM file under the certificate directory, sorted by name."""
    base = directory or cert_dir()
    if not base.is_dir():
        return {"cert_dir": str(base), "available": False, "files": []}
    files = []
    for path in sorted(base.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in PEM_SUFFIXES:
            continue
        rel = path.relative_to(base).as_posix()
        if any(part.startswith(".") for part in rel.split("/")):
            continue
        files.append(
            {"name": rel, "reference": FILE_REF_PREFIX + rel, **describe(path)}
        )
    return {"cert_dir": str(base), "available": True, "files": files}
