"""Auto-generated model script from SCL DataTypeTemplates and IED section.

Source file: 01_IED_.icd
Generated by: generate_mode_from_scl.py
"""

from __future__ import annotations

from dataclasses import asdict
from typing import Optional

from ws61850.iec61850.data_model import *

BTYPE_TO_DA_ENUM_NAME = {
    'BOOLEAN': 'boolean',
    'INT8': 'int8',
    'INT16': 'int16',
    'INT24': 'int24',
    'INT32': 'int32',
    'INT64': 'int64',
    'INT8U': 'int8u',
    'INT16U': 'int16u',
    'INT24U': 'int24u',
    'INT32U': 'int32u',
    'FLOAT32': 'float32',
    'FLOAT64': 'float32',
    'Enum': 'enumerated',
    'Quality': 'quality',
    'Timestamp': 'timeStamp',
    'Check': 'check',
    'Struct': 'structure',
    'VisString64': 'visString64',
    'VisString129': 'visString129',
    'VisString255': 'visString255',
    'Octet64': 'octetString',
    'OctetString': 'octetString',
    'ObjRef': 'visString255',
    'Dbpos': 'enumerated',
    'Tcmd': 'enumerated',
    'Unicode255': 'visString255',
    'PhyComAddr': 'octetString'
}
FC_TO_ENUM_NAME = {
    'ST': 'st',
    'MX': 'mx',
    'SP': 'sp',
    'SV': 'sv',
    'CF': 'cf',
    'DC': 'dc',
    'SG': 'sg',
    'SE': 'se',
    'SR': 'sr',
    'OR': 'or_',
    'BL': 'bl',
    'EX': 'ex',
    'LG': 'lg',
    'CO': 'co'
}

def _create_da_Originator(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_orcat_1 = DataAttribute('orCat', DataAttributeType.enumerated, fc, 0, da)
    da.add_data_attribute(_bda_orcat_1)
    _bda_orident_2 = DataAttribute('orIdent', DataAttributeType.octetString, fc, bytes(), da)
    da.add_data_attribute(_bda_orident_2)
    return da

def _create_da_OperBOOLEAN(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_ctlval_1 = DataAttribute('ctlVal', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_ctlval_1)
    _bda_origin_2 = _create_da_Originator('origin', fc, da)
    da.add_data_attribute(_bda_origin_2)
    _bda_ctlnum_3 = DataAttribute('ctlNum', DataAttributeType.int8u, fc, 0, da)
    da.add_data_attribute(_bda_ctlnum_3)
    _bda_t_4 = DataAttribute('T', DataAttributeType.timeStamp, fc, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, da)
    da.add_data_attribute(_bda_t_4)
    _bda_test_5 = DataAttribute('Test', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_test_5)
    _bda_check_6 = DataAttribute('Check', DataAttributeType.check, fc, {"synchroCheck": False, "interlockCheck": False}, da)
    da.add_data_attribute(_bda_check_6)
    return da

def _create_da_AnalogueValue(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_f_1 = DataAttribute('f', DataAttributeType.float32, fc, 0.0, da)
    da.add_data_attribute(_bda_f_1)
    return da

def _create_da_Vector(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_mag_1 = _create_da_AnalogueValue('mag', fc, da)
    da.add_data_attribute(_bda_mag_1)
    return da

def _create_do_ENS(name, parent):
    do = DataObject(name, 'ins', parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_DPC(name, parent):
    do = DataObject(name, 'dpc', parent=parent)
    _da_oper_1 = _create_da_OperBOOLEAN('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_1)
    _da_stval_2 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_stval_2)
    _da_q_3 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_3)
    _da_t_4 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_4)
    _da_ctlmodel_5 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 'direct-with-normal-security', do)
    do.add_do_or_da(_da_ctlmodel_5)
    return do

def _create_do_INS(name, parent):
    do = DataObject(name, 'ins', parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.int32, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_DPC1(name, parent):
    do = DataObject(name, 'dpc', parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_3)
    _da_ctlmodel_4 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 'direct-with-normal-security', do)
    do.add_do_or_da(_da_ctlmodel_4)
    return do

def _create_do_SPC(name, parent):
    do = DataObject(name, 'spc', parent=parent)
    _da_ctlmodel_1 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_1)
    return do

def _create_do_ENS1(name, parent):
    do = DataObject(name, 'ins', parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_MV(name, parent):
    do = DataObject(name, 'mv', parent=parent)
    _da_mag_1 = _create_da_AnalogueValue('mag', FunctionalConstraint.mx, do)
    do.add_do_or_da(_da_mag_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.mx, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.mx, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_CMV(name, parent):
    do = DataObject(name, 'cmv', parent=parent)
    _da_cval_1 = _create_da_Vector('cVal', FunctionalConstraint.mx, do)
    do.add_do_or_da(_da_cval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.mx, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.mx, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_WYE(name, parent):
    do = DataObject(name, 'wye', parent=parent)
    _sdo_phsa_1 = _create_do_by_typeref('phsA', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsa_1)
    _sdo_phsb_2 = _create_do_by_typeref('phsB', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsb_2)
    _sdo_phsc_3 = _create_do_by_typeref('phsC', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsc_3)
    return do

def _create_do_WYE1(name, parent):
    do = DataObject(name, 'wye', parent=parent)
    _sdo_phsa_1 = _create_do_by_typeref('phsA', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsa_1)
    _sdo_phsb_2 = _create_do_by_typeref('phsB', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsb_2)
    _sdo_phsc_3 = _create_do_by_typeref('phsC', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsc_3)
    _sdo_neut_4 = _create_do_by_typeref('neut', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_neut_4)
    _sdo_res_5 = _create_do_by_typeref('res', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_res_5)
    return do

def _create_do_SPC1(name, parent):
    do = DataObject(name, 'spc', parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, do)
    do.add_do_or_da(_da_t_3)
    _da_ctlmodel_4 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_4)
    return do

def _create_do_by_cdc(name: str, cdc: Optional[str], parent):
    cdc_norm = (cdc or '').lower()
    return DataObject(name, cdc_norm, parent=parent)

def _create_do_by_typeref(name: str, type_ref, cdc, parent):
    _dispatcher = {
        'ENS': _create_do_ENS,
        'DPC': _create_do_DPC,
        'INS': _create_do_INS,
        'DPC1': _create_do_DPC1,
        'SPC': _create_do_SPC,
        'ENS1': _create_do_ENS1,
        'MV': _create_do_MV,
        'CMV': _create_do_CMV,
        'WYE': _create_do_WYE,
        'WYE1': _create_do_WYE1,
        'SPC1': _create_do_SPC1,
    }
    fn = _dispatcher.get(type_ref)
    if fn:
        return fn(name, parent)
    return _create_do_by_cdc(name, cdc, parent)

def build_ied_model() -> IedModel:
    ied = IedModel(name='IED')

    ld1 = LogicalDevice(name='S640', ldName='S640')

    ln1_1 = LogicalNode(name='LLN0', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_1)
    ln1_1.add_data_object(do_beh_1)
    dataset_1_1_1 = DataSet(ln1_1, 'S640', 'XCBR1_DataSet')
    data_entry_1_1_1_1 = DataSetEntry('S640', 'S640/XCBR1.Pos.stVal', FunctionalConstraint.st)
    dataset_1_1_1.add_entry(data_entry_1_1_1_1)
    ln1_1.add_data_set(dataset_1_1_1)
    dataset_1_1_2 = DataSet(ln1_1, 'S640', 'MMXU2_DataSet')
    data_entry_1_1_2_1 = DataSetEntry('S640', 'S640/MMXU2.PhV.phsA.cVal', FunctionalConstraint.mx)
    dataset_1_1_2.add_entry(data_entry_1_1_2_1)
    data_entry_1_1_2_2 = DataSetEntry('S640', 'S640/MMXU2.PhV.phsB.cVal', FunctionalConstraint.mx)
    dataset_1_1_2.add_entry(data_entry_1_1_2_2)
    data_entry_1_1_2_3 = DataSetEntry('S640', 'S640/MMXU2.PhV.phsC.cVal', FunctionalConstraint.mx)
    dataset_1_1_2.add_entry(data_entry_1_1_2_3)
    ln1_1.add_data_set(dataset_1_1_2)
    dataset_1_1_3 = DataSet(ln1_1, 'S640', 'MMXU1_DataSet')
    data_entry_1_1_3_1 = DataSetEntry('S640', 'S640/MMXU1.TotPF.mag', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_1)
    data_entry_1_1_3_2 = DataSetEntry('S640', 'S640/MMXU1.TotVA.mag', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_2)
    data_entry_1_1_3_3 = DataSetEntry('S640', 'S640/MMXU1.TotVAr.mag', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_3)
    data_entry_1_1_3_4 = DataSetEntry('S640', 'S640/MMXU1.TotW.mag', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_4)
    data_entry_1_1_3_5 = DataSetEntry('S640', 'S640/MMXU1.Hz.mag', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_5)
    data_entry_1_1_3_6 = DataSetEntry('S640', 'S640/MMXU1.PhV.phsA.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_6)
    data_entry_1_1_3_7 = DataSetEntry('S640', 'S640/MMXU1.PhV.phsB.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_7)
    data_entry_1_1_3_8 = DataSetEntry('S640', 'S640/MMXU1.PhV.phsC.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_8)
    data_entry_1_1_3_9 = DataSetEntry('S640', 'S640/MMXU1.A.phsA.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_9)
    data_entry_1_1_3_10 = DataSetEntry('S640', 'S640/MMXU1.A.phsB.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_10)
    data_entry_1_1_3_11 = DataSetEntry('S640', 'S640/MMXU1.A.phsC.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_11)
    data_entry_1_1_3_12 = DataSetEntry('S640', 'S640/MMXU1.A.neut.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_12)
    data_entry_1_1_3_13 = DataSetEntry('S640', 'S640/MMXU1.A.res.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_13)
    data_entry_1_1_3_14 = DataSetEntry('S640', 'S640/MMXU2.PhV.phsA.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_14)
    data_entry_1_1_3_15 = DataSetEntry('S640', 'S640/MMXU2.PhV.phsB.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_15)
    data_entry_1_1_3_16 = DataSetEntry('S640', 'S640/MMXU2.PhV.phsC.cVal', FunctionalConstraint.mx)
    dataset_1_1_3.add_entry(data_entry_1_1_3_16)
    ln1_1.add_data_set(dataset_1_1_3)
    dataset_1_1_4 = DataSet(ln1_1, 'S640', 'GSE_DataSet')
    data_entry_1_1_4_1 = DataSetEntry('S640', 'S640/GSEO_GGIO1.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_1)
    data_entry_1_1_4_2 = DataSetEntry('S640', 'S640/GSEO_GGIO2.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_2)
    data_entry_1_1_4_3 = DataSetEntry('S640', 'S640/GSEO_GGIO3.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_3)
    data_entry_1_1_4_4 = DataSetEntry('S640', 'S640/GSEO_GGIO4.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_4)
    data_entry_1_1_4_5 = DataSetEntry('S640', 'S640/GSEO_GGIO5.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_5)
    data_entry_1_1_4_6 = DataSetEntry('S640', 'S640/GSEO_GGIO6.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_6)
    data_entry_1_1_4_7 = DataSetEntry('S640', 'S640/GSEO_GGIO7.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_7)
    data_entry_1_1_4_8 = DataSetEntry('S640', 'S640/GSEO_GGIO8.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_8)
    data_entry_1_1_4_9 = DataSetEntry('S640', 'S640/GSEO_GGIO9.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_9)
    data_entry_1_1_4_10 = DataSetEntry('S640', 'S640/GSEO_GGIO10.SPCSO.stVal', FunctionalConstraint.st)
    dataset_1_1_4.add_entry(data_entry_1_1_4_10)
    ln1_1.add_data_set(dataset_1_1_4)
    rcb_1_1_1 = ReportControl(
        'ucrbXCBR1',
        buffered=False,
        dataset_name='S640/LLN0.XCBR1_DataSet',
        rpt_id='ucrbXCBR1',
        conf_rev=1,
        trg_ops={
            'dchg': True,
            'dupd': False,
            'gi': False,
            'integrity': False,
            'qchg': False
        },
        opt_flds={
            'seqNum': True,
            'timeStamp': True,
            'dataSet': True,
            'reasonCode': True,
            'dataRef': True,
            'entryID': True,
            'configRef': True,
            'bufOvfl': False
        },
        buffered_time=1000,
        int_period=5000,
        indexed=False,
    )
    ln1_1.add_report_control(rcb_1_1_1)
    rcb_1_1_2 = ReportControl(
        'ucrbMMXU1',
        buffered=False,
        dataset_name='S640/LLN0.MMXU1_DataSet',
        rpt_id='ucrbMMXU1',
        conf_rev=1,
        trg_ops={
            'dchg': True,
            'dupd': False,
            'gi': False,
            'integrity': False,
            'qchg': False
        },
        opt_flds={
            'seqNum': True,
            'timeStamp': True,
            'dataSet': True,
            'reasonCode': True,
            'dataRef': True,
            'entryID': True,
            'configRef': True,
            'bufOvfl': False
        },
        buffered_time=1000,
        int_period=5000,
        indexed=False,
    )
    ln1_1.add_report_control(rcb_1_1_2)
    rcb_1_1_3 = ReportControl(
        'bcrbMMXU1',
        buffered=True,
        dataset_name='S640/LLN0.MMXU1_DataSet',
        rpt_id='bcrbMMXU1',
        conf_rev=1,
        trg_ops={
            'dchg': True,
            'dupd': False,
            'gi': False,
            'integrity': False,
            'qchg': False
        },
        opt_flds={
            'seqNum': True,
            'timeStamp': True,
            'dataSet': True,
            'reasonCode': True,
            'dataRef': True,
            'entryID': True,
            'configRef': True,
            'bufOvfl': False
        },
        buffered_time=1000,
        int_period=5000,
        indexed=False,
    )
    ln1_1.add_report_control(rcb_1_1_3)
    ld1.add_logical_node(ln1_1)
    ln1_2 = LogicalNode(name='CSWI1', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_2)
    ln1_2.add_data_object(do_beh_1)
    do_pos_2 = _create_do_by_typeref('Pos', 'DPC', 'DPC', ln1_2)
    ln1_2.add_data_object(do_pos_2)
    ld1.add_logical_node(ln1_2)
    ln1_3 = LogicalNode(name='XCBR1', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_3)
    ln1_3.add_data_object(do_beh_1)
    do_opcnt_2 = _create_do_by_typeref('OpCnt', 'INS', 'INS', ln1_3)
    ln1_3.add_data_object(do_opcnt_2)
    do_pos_3 = _create_do_by_typeref('Pos', 'DPC1', 'DPC', ln1_3)
    ln1_3.add_data_object(do_pos_3)
    do_blkopn_4 = _create_do_by_typeref('BlkOpn', 'SPC', 'SPC', ln1_3)
    ln1_3.add_data_object(do_blkopn_4)
    do_blkcls_5 = _create_do_by_typeref('BlkCls', 'SPC', 'SPC', ln1_3)
    ln1_3.add_data_object(do_blkcls_5)
    do_cbopcap_6 = _create_do_by_typeref('CBOpCap', 'ENS1', 'INS', ln1_3)
    ln1_3.add_data_object(do_cbopcap_6)
    ld1.add_logical_node(ln1_3)
    ln1_4 = LogicalNode(name='MMXU1', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_4)
    ln1_4.add_data_object(do_beh_1)
    do_totpf_2 = _create_do_by_typeref('TotPF', 'MV', 'MV', ln1_4)
    ln1_4.add_data_object(do_totpf_2)
    do_totva_3 = _create_do_by_typeref('TotVA', 'MV', 'MV', ln1_4)
    ln1_4.add_data_object(do_totva_3)
    do_totvar_4 = _create_do_by_typeref('TotVAr', 'MV', 'MV', ln1_4)
    ln1_4.add_data_object(do_totvar_4)
    do_totw_5 = _create_do_by_typeref('TotW', 'MV', 'MV', ln1_4)
    ln1_4.add_data_object(do_totw_5)
    do_hz_6 = _create_do_by_typeref('Hz', 'MV', 'MV', ln1_4)
    ln1_4.add_data_object(do_hz_6)
    do_phv_7 = _create_do_by_typeref('PhV', 'WYE', 'WYE', ln1_4)
    ln1_4.add_data_object(do_phv_7)
    do_a_8 = _create_do_by_typeref('A', 'WYE1', 'WYE', ln1_4)
    ln1_4.add_data_object(do_a_8)
    ld1.add_logical_node(ln1_4)
    ln1_5 = LogicalNode(name='MMXU2', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_5)
    ln1_5.add_data_object(do_beh_1)
    do_phv_2 = _create_do_by_typeref('PhV', 'WYE', 'WYE', ln1_5)
    ln1_5.add_data_object(do_phv_2)
    ld1.add_logical_node(ln1_5)
    ln1_6 = LogicalNode(name='GSEO_GGIO1', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_6)
    ln1_6.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_6)
    ln1_6.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_6)
    ln1_7 = LogicalNode(name='GSEO_GGIO2', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_7)
    ln1_7.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_7)
    ln1_7.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_7)
    ln1_8 = LogicalNode(name='GSEO_GGIO3', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_8)
    ln1_8.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_8)
    ln1_8.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_8)
    ln1_9 = LogicalNode(name='GSEO_GGIO4', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_9)
    ln1_9.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_9)
    ln1_9.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_9)
    ln1_10 = LogicalNode(name='GSEO_GGIO5', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_10)
    ln1_10.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_10)
    ln1_10.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_10)
    ln1_11 = LogicalNode(name='GSEO_GGIO6', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_11)
    ln1_11.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_11)
    ln1_11.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_11)
    ln1_12 = LogicalNode(name='GSEO_GGIO7', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_12)
    ln1_12.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_12)
    ln1_12.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_12)
    ln1_13 = LogicalNode(name='GSEO_GGIO8', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_13)
    ln1_13.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_13)
    ln1_13.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_13)
    ln1_14 = LogicalNode(name='GSEO_GGIO9', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_14)
    ln1_14.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_14)
    ln1_14.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_14)
    ln1_15 = LogicalNode(name='GSEO_GGIO10', parent=ld1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS', 'INS', ln1_15)
    ln1_15.add_data_object(do_beh_1)
    do_spcso_2 = _create_do_by_typeref('SPCSO', 'SPC1', 'SPC', ln1_15)
    ln1_15.add_data_object(do_spcso_2)
    ld1.add_logical_node(ln1_15)

    ied.add_logical_device(ld1)

    return ied


ied = build_ied_model()

