"""Auto-generated model script from SCL DataTypeTemplates and IED section.

Source file: C:/Users/MAXSON~1/AppData/Local/Temp/tmpn0twtalr/simpleIO_direct_control 2.cid
Generated by: generate_mode_from_scl.py
"""

from __future__ import annotations

from dataclasses import asdict
from typing import Optional

from ws61850.iec61850.data_model.model_functions import *


BTYPE_TO_DA_ENUM_NAME = {'BOOLEAN': 'boolean',
 'Check': 'check',
 'Dbpos': 'enumerated',
 'Enum': 'enumerated',
 'FLOAT32': 'float32',
 'FLOAT64': 'float32',
 'INT16': 'int16',
 'INT16U': 'int16u',
 'INT24': 'int24',
 'INT24U': 'int24u',
 'INT32': 'int32',
 'INT32U': 'int32u',
 'INT64': 'int64',
 'INT8': 'int8',
 'INT8U': 'int8u',
 'ObjRef': 'visString255',
 'Octet64': 'octetString',
 'OctetString': 'octetString',
 'PhyComAddr': 'octetString',
 'Quality': 'quality',
 'Struct': 'structure',
 'Tcmd': 'enumerated',
 'Timestamp': 'timeStamp',
 'Unicode255': 'visString255',
 'VisString129': 'visString129',
 'VisString255': 'visString255',
 'VisString64': 'visString64'}
FC_TO_ENUM_NAME = {'BL': 'bl',
 'CF': 'cf',
 'CO': 'co',
 'DC': 'dc',
 'EX': 'ex',
 'LG': 'lg',
 'MX': 'mx',
 'OR': 'or_',
 'SE': 'se',
 'SG': 'sg',
 'SP': 'sp',
 'SR': 'sr',
 'ST': 'st',
 'SV': 'sv'}


def _create_da_AnalogueValue_1(name, fc, parent):
    da = DataAttribute(name, 0, -1, DataAttributeType.structure, fc, 0, [], 0, parent)
    _bda_f = DataAttribute('f', 0, -1, DataAttributeType.float32, fc, 0, 0.0, 0, da)
    da.add_dataAttribute(_bda_f)
    return da

def _create_da_Originator_1(name, fc, parent):
    da = DataAttribute(name, 0, -1, DataAttributeType.structure, fc, 0, [], 0, parent)
    _bda_orCat = DataAttribute('orCat', 0, -1, DataAttributeType.enumerated, fc, 0, 0, 0, da)
    da.add_dataAttribute(_bda_orCat)
    _bda_orIdent = DataAttribute('orIdent', 0, -1, DataAttributeType.octetString, fc, 0, bytes(), 0, da)
    da.add_dataAttribute(_bda_orIdent)
    return da

def _create_da_SPCOperate_1(name, fc, parent):
    da = DataAttribute(name, 0, -1, DataAttributeType.structure, fc, 0, [], 0, parent)
    _bda_ctlVal = DataAttribute('ctlVal', 0, -1, DataAttributeType.boolean, fc, 0, False, 0, da)
    da.add_dataAttribute(_bda_ctlVal)
    _bda_origin = _create_da_Originator_1('origin', fc, da)
    da.add_dataAttribute(_bda_origin)
    _bda_ctlNum = DataAttribute('ctlNum', 0, -1, DataAttributeType.int8u, fc, 0, 0, 0, da)
    da.add_dataAttribute(_bda_ctlNum)
    _bda_T = DataAttribute('T', 0, -1, DataAttributeType.timeStamp, fc, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, da)
    da.add_dataAttribute(_bda_T)
    _bda_Test = DataAttribute('Test', 0, -1, DataAttributeType.boolean, fc, 0, False, 0, da)
    da.add_dataAttribute(_bda_Test)
    _bda_Check = DataAttribute('Check', 0, -1, DataAttributeType.check, fc, 0, {"synchroCheck": False, "interlockCheck": False}, 0, da)
    da.add_dataAttribute(_bda_Check)
    return da


def _create_do_ENC_1_Mod(name, parent):
    do = DataObject(name, 0, -1, cdc='enc', parent=parent)
    _da_stVal = DataAttribute('stVal', 0, -1, DataAttributeType.enumerated, FunctionalConstraint.st, 0, 0, 0, do)
    do.add_do_or_da(_da_stVal)
    _da_q = DataAttribute('q', 0, -1, DataAttributeType.quality, FunctionalConstraint.st, 0, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, 0, do)
    do.add_do_or_da(_da_q)
    _da_t = DataAttribute('t', 0, -1, DataAttributeType.timeStamp, FunctionalConstraint.st, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, do)
    do.add_do_or_da(_da_t)
    _da_ctlModel = DataAttribute('ctlModel', 0, -1, DataAttributeType.enumerated, FunctionalConstraint.cf, 0, 0, 0, do)
    do.add_do_or_da(_da_ctlModel)
    return do

def _create_do_ENS_1_Beh(name, parent):
    do = DataObject(name, 0, -1, cdc='ens', parent=parent)
    _da_stVal = DataAttribute('stVal', 0, -1, DataAttributeType.enumerated, FunctionalConstraint.st, 0, 0, 0, do)
    do.add_do_or_da(_da_stVal)
    _da_q = DataAttribute('q', 0, -1, DataAttributeType.quality, FunctionalConstraint.st, 0, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, 0, do)
    do.add_do_or_da(_da_q)
    _da_t = DataAttribute('t', 0, -1, DataAttributeType.timeStamp, FunctionalConstraint.st, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, do)
    do.add_do_or_da(_da_t)
    return do

def _create_do_ENS_2_Health(name, parent):
    do = DataObject(name, 0, -1, cdc='ens', parent=parent)
    _da_stVal = DataAttribute('stVal', 0, -1, DataAttributeType.enumerated, FunctionalConstraint.st, 0, 0, 0, do)
    do.add_do_or_da(_da_stVal)
    _da_q = DataAttribute('q', 0, -1, DataAttributeType.quality, FunctionalConstraint.st, 0, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, 0, do)
    do.add_do_or_da(_da_q)
    _da_t = DataAttribute('t', 0, -1, DataAttributeType.timeStamp, FunctionalConstraint.st, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, do)
    do.add_do_or_da(_da_t)
    return do

def _create_do_LPL_1_NamPlt(name, parent):
    do = DataObject(name, 0, -1, cdc='lpl', parent=parent)
    _da_vendor = DataAttribute('vendor', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_vendor)
    _da_swRev = DataAttribute('swRev', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_swRev)
    _da_d = DataAttribute('d', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_d)
    _da_configRev = DataAttribute('configRev', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_configRev)
    _da_ldNs = DataAttribute('ldNs', 0, -1, DataAttributeType.visString255, FunctionalConstraint.ex, 0, "", 0, do)
    do.add_do_or_da(_da_ldNs)
    return do

def _create_do_DPL_1_PhyNam(name, parent):
    do = DataObject(name, 0, -1, cdc='dpl', parent=parent)
    _da_vendor = DataAttribute('vendor', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_vendor)
    return do

def _create_do_SPS_1_Proxy(name, parent):
    do = DataObject(name, 0, -1, cdc='sps', parent=parent)
    _da_stVal = DataAttribute('stVal', 0, -1, DataAttributeType.boolean, FunctionalConstraint.st, 0, False, 0, do)
    do.add_do_or_da(_da_stVal)
    _da_q = DataAttribute('q', 0, -1, DataAttributeType.quality, FunctionalConstraint.st, 0, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, 0, do)
    do.add_do_or_da(_da_q)
    _da_t = DataAttribute('t', 0, -1, DataAttributeType.timeStamp, FunctionalConstraint.st, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, do)
    do.add_do_or_da(_da_t)
    return do

def _create_do_LPL_2_NamPlt(name, parent):
    do = DataObject(name, 0, -1, cdc='lpl', parent=parent)
    _da_vendor = DataAttribute('vendor', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_vendor)
    _da_swRev = DataAttribute('swRev', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_swRev)
    _da_d = DataAttribute('d', 0, -1, DataAttributeType.visString255, FunctionalConstraint.dc, 0, "", 0, do)
    do.add_do_or_da(_da_d)
    return do

def _create_do_MV_1_AnIn1(name, parent):
    do = DataObject(name, 0, -1, cdc='mv', parent=parent)
    _da_mag = _create_da_AnalogueValue_1('mag', FunctionalConstraint.mx, do)
    do.add_do_or_da(_da_mag)
    _da_q = DataAttribute('q', 0, -1, DataAttributeType.quality, FunctionalConstraint.mx, 0, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, 0, do)
    do.add_do_or_da(_da_q)
    _da_t = DataAttribute('t', 0, -1, DataAttributeType.timeStamp, FunctionalConstraint.mx, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, do)
    do.add_do_or_da(_da_t)
    return do

def _create_do_SPC_1_SPCSO1(name, parent):
    do = DataObject(name, 0, -1, cdc='spc', parent=parent)
    _da_origin = _create_da_Originator_1('origin', FunctionalConstraint.st, do)
    do.add_do_or_da(_da_origin)
    _da_ctlNum = DataAttribute('ctlNum', 0, -1, DataAttributeType.int8u, FunctionalConstraint.st, 0, 0, 0, do)
    do.add_do_or_da(_da_ctlNum)
    _da_stVal = DataAttribute('stVal', 0, -1, DataAttributeType.boolean, FunctionalConstraint.st, 0, False, 0, do)
    do.add_do_or_da(_da_stVal)
    _da_q = DataAttribute('q', 0, -1, DataAttributeType.quality, FunctionalConstraint.st, 0, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, 0, do)
    do.add_do_or_da(_da_q)
    _da_t = DataAttribute('t', 0, -1, DataAttributeType.timeStamp, FunctionalConstraint.st, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, do)
    do.add_do_or_da(_da_t)
    _da_ctlModel = DataAttribute('ctlModel', 0, -1, DataAttributeType.enumerated, FunctionalConstraint.cf, 0, 0, 0, do)
    do.add_do_or_da(_da_ctlModel)
    _da_Oper = _create_da_SPCOperate_1('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_Oper)
    return do

def _create_do_SPC_2(name, parent):
    do = DataObject(name, 0, -1, cdc='spc', parent=parent)
    _da_stVal = DataAttribute('stVal', 0, -1, DataAttributeType.boolean, FunctionalConstraint.st, 0, False, 0, do)
    do.add_do_or_da(_da_stVal)
    _da_q = DataAttribute('q', 0, -1, DataAttributeType.quality, FunctionalConstraint.st, 0, {"validity": "good", "source": "process", "test": False, "operatorBlock": False}, 0, do)
    do.add_do_or_da(_da_q)
    _da_Oper = _create_da_SPCOperate_1('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_Oper)
    _da_ctlModel = DataAttribute('ctlModel', 0, -1, DataAttributeType.enumerated, FunctionalConstraint.cf, 0, 0, 0, do)
    do.add_do_or_da(_da_ctlModel)
    _da_t = DataAttribute('t', 0, -1, DataAttributeType.timeStamp, FunctionalConstraint.st, 0, {"secondSinceEpoch": 0, "fractionOfSecond": 0, "timeQuality": {"leapSecondsKown": False, "clockFailure": False, "clockNotSynchronized": False, "timeAccuracy": 0}}, 0, do)
    do.add_do_or_da(_da_t)
    return do


def _create_do_by_cdc(name: str, cdc: Optional[str], parent):
    cdc_norm = (cdc or '').lower()
    if cdc_norm == 'mv':
        return create_mv_do(name, parent)
    if cdc_norm == 'asg':
        return create_asg_do(name, parent)
    if cdc_norm == 'apc':
        return create_apc_do(name, parent)
    if cdc_norm == 'inc':
        return create_inc_do(name, parent)
    if cdc_norm == 'ens':
        return create_ens_do(name, parent)
    if cdc_norm == 'sps':
        return create_sps_do(name, parent)
    if cdc_norm == 'enc':
        return create_enc_do(name, parent)
    if cdc_norm == 'lpl':
        return create_lpl_do(name, parent)
    if cdc_norm == 'dpl':
        return create_dpl_do(name, parent)
    if cdc_norm == 'cmv':
        return create_cmv_do(name, parent)
    if cdc_norm == 'ing':
        return create_ing_do(name, parent)
    if cdc_norm == 'wye':
        return create_wye_do(name, parent)
    if cdc_norm == 'del':
        return create_del_do(name, parent)
    return DataObject(name, 0, -1, cdc=cdc_norm or None, parent=parent)


def _create_do_by_typeref(name: str, type_ref, cdc, parent):
    _dispatcher = {
        'ENC_1_Mod': _create_do_ENC_1_Mod,
        'ENS_1_Beh': _create_do_ENS_1_Beh,
        'ENS_2_Health': _create_do_ENS_2_Health,
        'LPL_1_NamPlt': _create_do_LPL_1_NamPlt,
        'DPL_1_PhyNam': _create_do_DPL_1_PhyNam,
        'SPS_1_Proxy': _create_do_SPS_1_Proxy,
        'LPL_2_NamPlt': _create_do_LPL_2_NamPlt,
        'MV_1_AnIn1': _create_do_MV_1_AnIn1,
        'SPC_1_SPCSO1': _create_do_SPC_1_SPCSO1,
        'SPC_2': _create_do_SPC_2,
    }
    fn = _dispatcher.get(type_ref)
    if fn:
        return fn(name, parent)
    return _create_do_by_cdc(name, cdc, parent)


def build_ied_model() -> IedModel:
    ied = IedModel(name='simpleIO')

    ld1 = LogicalDevice(name='GenericIO', ldName='GenericIO')
    ln1 = LogicalNode(name='LLN0', parent=ld1)
    do_mod_1 = _create_do_by_typeref('Mod', 'ENC_1_Mod', 'ENC', ln1)
    ln1.add_dataObject(do_mod_1)
    do_beh_1 = _create_do_by_typeref('Beh', 'ENS_1_Beh', 'ENS', ln1)
    ln1.add_dataObject(do_beh_1)
    do_health_1 = _create_do_by_typeref('Health', 'ENS_2_Health', 'ENS', ln1)
    ln1.add_dataObject(do_health_1)
    do_namplt_1 = _create_do_by_typeref('NamPlt', 'LPL_1_NamPlt', 'LPL', ln1)
    ln1.add_dataObject(do_namplt_1)

    dataset_events_1_1 = DataSet(ln1, 'GenericIO', 'Events', 4)
    data_entry_1 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO1.stVal', -1, None, None, FunctionalConstraint.st)
    dataset_events_1_1.dataSet_addEntry(data_entry_1)
    data_entry_2 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO2.stVal', -1, None, None, FunctionalConstraint.st)
    dataset_events_1_1.dataSet_addEntry(data_entry_2)
    data_entry_3 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO3.stVal', -1, None, None, FunctionalConstraint.st)
    dataset_events_1_1.dataSet_addEntry(data_entry_3)
    data_entry_4 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO4.stVal', -1, None, None, FunctionalConstraint.st)
    dataset_events_1_1.dataSet_addEntry(data_entry_4)
    ln1.add_dataSet(dataset_events_1_1)

    dataset_events2_1_2 = DataSet(ln1, 'GenericIO', 'Events2', 4)
    data_entry_1 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO1', -1, None, None, FunctionalConstraint.st)
    dataset_events2_1_2.dataSet_addEntry(data_entry_1)
    data_entry_2 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO2', -1, None, None, FunctionalConstraint.st)
    dataset_events2_1_2.dataSet_addEntry(data_entry_2)
    data_entry_3 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO3', -1, None, None, FunctionalConstraint.st)
    dataset_events2_1_2.dataSet_addEntry(data_entry_3)
    data_entry_4 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.SPCSO4', -1, None, None, FunctionalConstraint.st)
    dataset_events2_1_2.dataSet_addEntry(data_entry_4)
    ln1.add_dataSet(dataset_events2_1_2)

    dataset_measurements_1_3 = DataSet(ln1, 'GenericIO', 'Measurements', 8)
    data_entry_1 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn1.mag.f', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_1)
    data_entry_2 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn1.q', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_2)
    data_entry_3 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn2.mag.f', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_3)
    data_entry_4 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn2.q', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_4)
    data_entry_5 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn3.mag.f', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_5)
    data_entry_6 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn3.q', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_6)
    data_entry_7 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn4.mag.f', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_7)
    data_entry_8 = DataSetEntry('GenericIO', False, 'GenericIO/GGIO1.AnIn4.q', -1, None, None, FunctionalConstraint.mx)
    dataset_measurements_1_3.dataSet_addEntry(data_entry_8)
    ln1.add_dataSet(dataset_measurements_1_3)

    opt_fields_1_1 = asdict(OptFldsRCB(True, True, True, False, True, False, False, True))
    trg_opts_1_1 = {'dchg': False, 'dupd': False, 'gi': False, 'integrity': True, 'qchg': False}
    rcb_eventsrcb_1_1 = ReportControl('GenericIO/LLN0.EventsRCB', ln1, 'EventsRCB', 'Events1', False, 'GenericIO/LLN0.Events', 1, trg_opts_1_1, opt_fields_1_1, 50, 1000, None, False)
    ln1.add_reportControl(rcb_eventsrcb_1_1)

    opt_fields_1_2 = asdict(OptFldsRCB(True, True, True, False, True, False, False, True))
    trg_opts_1_2 = {'dchg': False, 'dupd': False, 'gi': False, 'integrity': True, 'qchg': False}
    rcb_eventsrcbpreconf_1_2 = ReportControl('GenericIO/LLN0.EventsRCBPreConf', ln1, 'EventsRCBPreConf', 'Events1', False, 'GenericIO/LLN0.Events', 1, trg_opts_1_2, opt_fields_1_2, 50, 1000, None, False)
    ln1.add_reportControl(rcb_eventsrcbpreconf_1_2)

    opt_fields_1_3 = asdict(OptFldsRCB(True, True, True, False, True, False, False, True))
    trg_opts_1_3 = {'dchg': False, 'dupd': False, 'gi': False, 'integrity': True, 'qchg': False}
    rcb_eventsbrcb_1_3 = ReportControl('GenericIO/LLN0.EventsBRCB', ln1, 'EventsBRCB', 'Events2', True, 'GenericIO/LLN0.Events', 1, trg_opts_1_3, opt_fields_1_3, 50, 1000, None, False)
    ln1.add_reportControl(rcb_eventsbrcb_1_3)

    opt_fields_1_4 = asdict(OptFldsRCB(True, True, True, False, True, False, False, True))
    trg_opts_1_4 = {'dchg': False, 'dupd': False, 'gi': False, 'integrity': True, 'qchg': False}
    rcb_eventsbrcbpreconf_1_4 = ReportControl('GenericIO/LLN0.EventsBRCBPreConf', ln1, 'EventsBRCBPreConf', 'Events2', True, 'GenericIO/LLN0.Events', 1, trg_opts_1_4, opt_fields_1_4, 50, 1000, None, False)
    ln1.add_reportControl(rcb_eventsbrcbpreconf_1_4)

    opt_fields_1_5 = asdict(OptFldsRCB(True, True, True, False, True, False, False, True))
    trg_opts_1_5 = {'dchg': False, 'dupd': False, 'gi': False, 'integrity': True, 'qchg': False}
    rcb_eventsindexed_1_5 = ReportControl('GenericIO/LLN0.EventsIndexed', ln1, 'EventsIndexed', 'Events2', False, 'GenericIO/LLN0.Events', 1, trg_opts_1_5, opt_fields_1_5, 50, 1000, None, True)
    ln1.add_reportControl(rcb_eventsindexed_1_5)

    opt_fields_1_6 = asdict(OptFldsRCB(True, True, True, False, True, True, False, True))
    trg_opts_1_6 = {'dchg': False, 'dupd': False, 'gi': False, 'integrity': False, 'qchg': False}
    rcb_measurements_1_6 = ReportControl('GenericIO/LLN0.Measurements', ln1, 'Measurements', 'Measurements', True, 'GenericIO/LLN0.Measurements', 1, trg_opts_1_6, opt_fields_1_6, 50, 1000, None, True)
    ln1.add_reportControl(rcb_measurements_1_6)
    ln2 = LogicalNode(name='LPHD1', parent=ld1)
    do_phynam_2 = _create_do_by_typeref('PhyNam', 'DPL_1_PhyNam', 'DPL', ln2)
    ln2.add_dataObject(do_phynam_2)
    do_phyhealth_2 = _create_do_by_typeref('PhyHealth', 'ENS_2_Health', 'ENS', ln2)
    ln2.add_dataObject(do_phyhealth_2)
    do_proxy_2 = _create_do_by_typeref('Proxy', 'SPS_1_Proxy', 'SPS', ln2)
    ln2.add_dataObject(do_proxy_2)
    ln3 = LogicalNode(name='GGIO1', parent=ld1)
    do_mod_3 = _create_do_by_typeref('Mod', 'ENC_1_Mod', 'ENC', ln3)
    ln3.add_dataObject(do_mod_3)
    do_beh_3 = _create_do_by_typeref('Beh', 'ENS_1_Beh', 'ENS', ln3)
    ln3.add_dataObject(do_beh_3)
    do_health_3 = _create_do_by_typeref('Health', 'ENS_2_Health', 'ENS', ln3)
    ln3.add_dataObject(do_health_3)
    do_namplt_3 = _create_do_by_typeref('NamPlt', 'LPL_2_NamPlt', 'LPL', ln3)
    ln3.add_dataObject(do_namplt_3)
    do_anin1_3 = _create_do_by_typeref('AnIn1', 'MV_1_AnIn1', 'MV', ln3)
    ln3.add_dataObject(do_anin1_3)
    do_anin2_3 = _create_do_by_typeref('AnIn2', 'MV_1_AnIn1', 'MV', ln3)
    ln3.add_dataObject(do_anin2_3)
    do_anin3_3 = _create_do_by_typeref('AnIn3', 'MV_1_AnIn1', 'MV', ln3)
    ln3.add_dataObject(do_anin3_3)
    do_anin4_3 = _create_do_by_typeref('AnIn4', 'MV_1_AnIn1', 'MV', ln3)
    ln3.add_dataObject(do_anin4_3)
    do_spcso1_3 = _create_do_by_typeref('SPCSO1', 'SPC_1_SPCSO1', 'SPC', ln3)
    ln3.add_dataObject(do_spcso1_3)
    do_spcso2_3 = _create_do_by_typeref('SPCSO2', 'SPC_2', 'SPC', ln3)
    ln3.add_dataObject(do_spcso2_3)
    do_spcso3_3 = _create_do_by_typeref('SPCSO3', 'SPC_2', 'SPC', ln3)
    ln3.add_dataObject(do_spcso3_3)
    do_spcso4_3 = _create_do_by_typeref('SPCSO4', 'SPC_2', 'SPC', ln3)
    ln3.add_dataObject(do_spcso4_3)
    do_ind1_3 = _create_do_by_typeref('Ind1', 'SPS_1_Proxy', 'SPS', ln3)
    ln3.add_dataObject(do_ind1_3)
    do_ind2_3 = _create_do_by_typeref('Ind2', 'SPS_1_Proxy', 'SPS', ln3)
    ln3.add_dataObject(do_ind2_3)
    do_ind3_3 = _create_do_by_typeref('Ind3', 'SPS_1_Proxy', 'SPS', ln3)
    ln3.add_dataObject(do_ind3_3)
    do_ind4_3 = _create_do_by_typeref('Ind4', 'SPS_1_Proxy', 'SPS', ln3)
    ln3.add_dataObject(do_ind4_3)

    ld1.add_logical_node(ln1)
    ld1.add_logical_node(ln2)
    ld1.add_logical_node(ln3)
    ied.add_logicalDevice(ld1)

    return ied


ied = build_ied_model()
