"""Auto-generated model script from SCL DataTypeTemplates and IED section.
Source file: simpleIO_control_tests.scd
Generated by: SCL Model Factory"""

from __future__ import annotations

from dataclasses import asdict
from typing import Optional

from ws61850.iec61850.data_model import *
from ws61850.protocol.types import OptFlds

BTYPE_TO_DA_ENUM_NAME = {"BOOLEAN":"boolean","INT8":"int8","INT16":"int16","INT24":"int24","INT32":"int32","INT64":"int64","INT8U":"int8u","INT16U":"int16u","INT24U":"int24u","INT32U":"int32u","FLOAT32":"float32","FLOAT64":"float64","Enum":"enumerated","Quality":"quality","Timestamp":"timeStamp","Check":"check","Struct":"structure","VisString64":"visString64","VisString129":"visString129","VisString255":"visString255","Octet64":"octetString","OctetString":"octetString","ObjRef":"visString255","Dbpos":"enumerated","Tcmd":"enumerated","Unicode255":"visString255","PhyComAddr":"octetString"}
FC_TO_ENUM_NAME = {"ST":"st","MX":"mx","SP":"sp","SV":"sv","CF":"cf","DC":"dc","SG":"sg","SE":"se","SR":"sr","OR":"or_","BL":"bl","EX":"ex","LG":"lg","CO":"co"}

def _create_da_Vector(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_mag_1 = _create_da_AnalogueValue('mag', fc, da)
    da.add_data_attribute(_bda_mag_1)
    _bda_ang_2 = _create_da_AnalogueValue('ang', fc, da)
    da.add_data_attribute(_bda_ang_2)
    return da

def _create_da_SPCOperate_1(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_ctlval_1 = DataAttribute('ctlVal', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_ctlval_1)
    _bda_origin_2 = _create_da_Originator_1('origin', fc, da)
    da.add_data_attribute(_bda_origin_2)
    _bda_ctlnum_3 = DataAttribute('ctlNum', DataAttributeType.int8u, fc, 0, da)
    da.add_data_attribute(_bda_ctlnum_3)
    _bda_t_4 = DataAttribute('T', DataAttributeType.timeStamp, fc, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, da)
    da.add_data_attribute(_bda_t_4)
    _bda_test_5 = DataAttribute('Test', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_test_5)
    _bda_check_6 = DataAttribute('Check', DataAttributeType.check, fc, None, da)
    da.add_data_attribute(_bda_check_6)
    return da

def _create_da_Originator_1(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_orcat_1 = DataAttribute('orCat', DataAttributeType.enumerated, fc, 0, da)
    da.add_data_attribute(_bda_orcat_1)
    _bda_orident_2 = DataAttribute('orIdent', DataAttributeType.octetString, fc, b'', da)
    da.add_data_attribute(_bda_orident_2)
    return da

def _create_da_SPCOperate_5(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_ctlval_1 = DataAttribute('ctlVal', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_ctlval_1)
    _bda_opertm_2 = DataAttribute('operTm', DataAttributeType.timeStamp, fc, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, da)
    da.add_data_attribute(_bda_opertm_2)
    _bda_origin_3 = _create_da_Originator_1('origin', fc, da)
    da.add_data_attribute(_bda_origin_3)
    _bda_ctlnum_4 = DataAttribute('ctlNum', DataAttributeType.int8u, fc, 0, da)
    da.add_data_attribute(_bda_ctlnum_4)
    _bda_t_5 = DataAttribute('T', DataAttributeType.timeStamp, fc, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, da)
    da.add_data_attribute(_bda_t_5)
    _bda_test_6 = DataAttribute('Test', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_test_6)
    _bda_check_7 = DataAttribute('Check', DataAttributeType.check, fc, None, da)
    da.add_data_attribute(_bda_check_7)
    return da

def _create_da_SPCCancel_1(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_ctlval_1 = DataAttribute('ctlVal', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_ctlval_1)
    _bda_origin_2 = _create_da_Originator_1('origin', fc, da)
    da.add_data_attribute(_bda_origin_2)
    _bda_ctlnum_3 = DataAttribute('ctlNum', DataAttributeType.int8u, fc, 0, da)
    da.add_data_attribute(_bda_ctlnum_3)
    _bda_t_4 = DataAttribute('T', DataAttributeType.timeStamp, fc, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, da)
    da.add_data_attribute(_bda_t_4)
    _bda_test_5 = DataAttribute('Test', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_test_5)
    return da

def _create_da_SPCCancel_5(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_ctlval_1 = DataAttribute('ctlVal', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_ctlval_1)
    _bda_opertm_2 = DataAttribute('operTm', DataAttributeType.timeStamp, fc, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, da)
    da.add_data_attribute(_bda_opertm_2)
    _bda_origin_3 = _create_da_Originator_1('origin', fc, da)
    da.add_data_attribute(_bda_origin_3)
    _bda_ctlnum_4 = DataAttribute('ctlNum', DataAttributeType.int8u, fc, 0, da)
    da.add_data_attribute(_bda_ctlnum_4)
    _bda_t_5 = DataAttribute('T', DataAttributeType.timeStamp, fc, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, da)
    da.add_data_attribute(_bda_t_5)
    _bda_test_6 = DataAttribute('Test', DataAttributeType.boolean, fc, False, da)
    da.add_data_attribute(_bda_test_6)
    return da

def _create_da_AnalogueValue(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_f_1 = DataAttribute('f', DataAttributeType.float32, fc, 0.0, da)
    da.add_data_attribute(_bda_f_1)
    return da

def _create_do_SPG_1(name, parent):
    do = DataObject(name, "spg", parent=parent)
    _da_setval_1 = DataAttribute('setVal', DataAttributeType.boolean, FunctionalConstraint.sp, False, do)
    do.add_do_or_da(_da_setval_1)
    return do

def _create_do_ASG(name, parent):
    do = DataObject(name, "asg", parent=parent)
    _da_setmag_1 = _create_da_AnalogueValue('setMag', FunctionalConstraint.sp, do)
    do.add_do_or_da(_da_setmag_1)
    return do

def _create_do_ISP(name, parent):
    do = DataObject(name, "ins", parent=parent)
    _da_setval_1 = DataAttribute('setVal', DataAttributeType.int32, FunctionalConstraint.sp, 0, do)
    do.add_do_or_da(_da_setval_1)
    return do

def _create_do_HWYE_1_HA(name, parent):
    do = DataObject(name, "hwye", parent=parent)
    _da_numhar_1 = DataAttribute('numHar', DataAttributeType.int16u, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_numhar_1)
    _da_numcyc_2 = DataAttribute('numCyc', DataAttributeType.int16u, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_numcyc_2)
    _da_evaltm_3 = DataAttribute('evalTm', DataAttributeType.int16u, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_evaltm_3)
    _da_frequency_4 = DataAttribute('frequency', DataAttributeType.float32, FunctionalConstraint.cf, 0.0, do)
    do.add_do_or_da(_da_frequency_4)
    _sdo_phsahar_1 = _create_do_by_typeref('phsAHar', 'CMV_1_phsAHar', 'CMV', do)
    do.add_do_or_da(_sdo_phsahar_1)
    return do

def _create_do_SCA_1_SchdAbsTm(name, parent):
    do = DataObject(name, "sca", parent=parent)
    _da_val_1 = DataAttribute('val', DataAttributeType.float32, FunctionalConstraint.sp, 0.0, do)
    do.add_do_or_da(_da_val_1)
    return do

def _create_do_CMV_1_phsAHar(name, parent):
    do = DataObject(name, "cmv", parent=parent)
    _da_cval_1 = _create_da_Vector('cVal', FunctionalConstraint.mx, do)
    do.add_do_or_da(_da_cval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.mx, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.mx, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_INC_1_Mod(name, parent):
    do = DataObject(name, "inc", parent=parent)
    _da_q_1 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_1)
    _da_t_2 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_2)
    _da_ctlmodel_3 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_3)
    return do

def _create_do_INS_1_Beh(name, parent):
    do = DataObject(name, "ins", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.int32, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_INS_64(name, parent):
    do = DataObject(name, "ins", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.int64, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_LPL_1_NamPlt(name, parent):
    do = DataObject(name, "lpl", parent=parent)
    _da_vendor_1 = DataAttribute('vendor', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_vendor_1)
    _da_swrev_2 = DataAttribute('swRev', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_swrev_2)
    _da_d_3 = DataAttribute('d', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_d_3)
    _da_configrev_4 = DataAttribute('configRev', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_configrev_4)
    _da_ldns_5 = DataAttribute('ldNs', DataAttributeType.visString255, FunctionalConstraint.ex, '', do)
    do.add_do_or_da(_da_ldns_5)
    return do

def _create_do_DPL_1_PhyNam(name, parent):
    do = DataObject(name, "dpl", parent=parent)
    _da_vendor_1 = DataAttribute('vendor', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_vendor_1)
    return do

def _create_do_SPS_1_Proxy(name, parent):
    do = DataObject(name, "sps", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_SPC_1_SPCSO8(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_sbow_1 = _create_da_SPCOperate_5('SBOw', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_sbow_1)
    _da_oper_2 = _create_da_SPCOperate_5('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_2)
    _da_cancel_3 = _create_da_SPCCancel_5('Cancel', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_cancel_3)
    _da_origin_4 = _create_da_Originator_1('origin', FunctionalConstraint.st, do)
    do.add_do_or_da(_da_origin_4)
    _da_ctlnum_5 = DataAttribute('ctlNum', DataAttributeType.int8u, FunctionalConstraint.st, 0, do)
    do.add_do_or_da(_da_ctlnum_5)
    _da_stval_6 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_6)
    _da_q_7 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_7)
    _da_t_8 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_8)
    _da_ctlmodel_9 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_9)
    return do

def _create_do_SPC_1_SPCSO7(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_oper_1 = _create_da_SPCOperate_5('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_1)
    _da_cancel_2 = _create_da_SPCCancel_5('Cancel', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_cancel_2)
    _da_stval_3 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_3)
    _da_q_4 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_4)
    _da_t_5 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_5)
    _da_ctlmodel_6 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_6)
    return do

def _create_do_SPC_1_SPCSO3(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_oper_1 = _create_da_SPCOperate_1('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_1)
    _da_cancel_2 = _create_da_SPCCancel_1('Cancel', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_cancel_2)
    _da_stval_3 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_3)
    _da_q_4 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_4)
    _da_t_5 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_5)
    _da_ctlmodel_6 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_6)
    return do

def _create_do_MV_1_AnIn1(name, parent):
    do = DataObject(name, "mv", parent=parent)
    _da_mag_1 = DataAttribute('mag', DataAttributeType.structure, FunctionalConstraint.mx, None, do)
    do.add_do_or_da(_da_mag_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.mx, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.mx, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_SPC_1_SPCSO6(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_sbo_1 = DataAttribute('SBO', DataAttributeType.visString64, FunctionalConstraint.co, '', do)
    do.add_do_or_da(_da_sbo_1)
    _da_oper_2 = _create_da_SPCOperate_5('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_2)
    _da_cancel_3 = _create_da_SPCCancel_5('Cancel', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_cancel_3)
    _da_stval_4 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_4)
    _da_q_5 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_5)
    _da_t_6 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_6)
    _da_ctlmodel_7 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_7)
    return do

def _create_do_SPC_1_SPCSO5(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_oper_1 = _create_da_SPCOperate_5('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_1)
    _da_stval_2 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_2)
    _da_q_3 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_3)
    _da_t_4 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_4)
    _da_ctlmodel_5 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_5)
    _da_cancel_6 = _create_da_SPCCancel_1('Cancel', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_cancel_6)
    return do

def _create_do_SPC_1_SPCSO4(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_sbow_1 = _create_da_SPCOperate_1('SBOw', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_sbow_1)
    _da_oper_2 = _create_da_SPCOperate_1('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_2)
    _da_cancel_3 = _create_da_SPCCancel_1('Cancel', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_cancel_3)
    _da_stval_4 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_4)
    _da_q_5 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_5)
    _da_t_6 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_6)
    _da_ctlmodel_7 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_7)
    return do

def _create_do_LPL_2_NamPlt(name, parent):
    do = DataObject(name, "lpl", parent=parent)
    _da_vendor_1 = DataAttribute('vendor', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_vendor_1)
    _da_swrev_2 = DataAttribute('swRev', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_swrev_2)
    _da_d_3 = DataAttribute('d', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_d_3)
    _da_du_4 = DataAttribute('dU', DataAttributeType.visString255, FunctionalConstraint.dc, '', do)
    do.add_do_or_da(_da_du_4)
    return do

def _create_do_SPC_1_SPCSO2(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_sbo_1 = DataAttribute('SBO', DataAttributeType.visString64, FunctionalConstraint.co, '', do)
    do.add_do_or_da(_da_sbo_1)
    _da_oper_2 = _create_da_SPCOperate_1('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_2)
    _da_cancel_3 = _create_da_SPCCancel_1('Cancel', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_cancel_3)
    _da_stval_4 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_4)
    _da_q_5 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_5)
    _da_t_6 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_6)
    _da_ctlmodel_7 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_7)
    _da_sboclass_8 = DataAttribute('sboClass', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_sboclass_8)
    return do

def _create_do_SPC_1_SPCSO1(name, parent):
    do = DataObject(name, "spc", parent=parent)
    _da_oper_1 = _create_da_SPCOperate_1('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_1)
    _da_stval_2 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, False, do)
    do.add_do_or_da(_da_stval_2)
    _da_q_3 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, {
        'validity': 'good'
    }, do)
    do.add_do_or_da(_da_q_3)
    _da_t_4 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, {
        'secondSinceEpoch': 0,
        'fractionOfSecond': 0,
        'timeQuality': {
            'leapSecondsKnown': False,
            'clockFailure': False,
            'clockNotSynchronized': False,
            'timeAccuracy': 0
        }
    }, do)
    do.add_do_or_da(_da_t_4)
    _da_ctlmodel_5 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 0, do)
    do.add_do_or_da(_da_ctlmodel_5)
    return do

def _create_do_by_cdc(name: str, cdc: Optional[str], parent):
    cdc_norm = (cdc or '').lower()
    return DataObject(name, cdc_norm, parent=parent)

def _create_do_by_typeref(name: str, type_ref, cdc, parent):
    _dispatcher = {
        'SPG_1': _create_do_SPG_1,
        'ASG': _create_do_ASG,
        'ISP': _create_do_ISP,
        'HWYE_1_HA': _create_do_HWYE_1_HA,
        'SCA_1_SchdAbsTm': _create_do_SCA_1_SchdAbsTm,
        'CMV_1_phsAHar': _create_do_CMV_1_phsAHar,
        'INC_1_Mod': _create_do_INC_1_Mod,
        'INS_1_Beh': _create_do_INS_1_Beh,
        'INS_64': _create_do_INS_64,
        'LPL_1_NamPlt': _create_do_LPL_1_NamPlt,
        'DPL_1_PhyNam': _create_do_DPL_1_PhyNam,
        'SPS_1_Proxy': _create_do_SPS_1_Proxy,
        'SPC_1_SPCSO8': _create_do_SPC_1_SPCSO8,
        'SPC_1_SPCSO7': _create_do_SPC_1_SPCSO7,
        'SPC_1_SPCSO3': _create_do_SPC_1_SPCSO3,
        'MV_1_AnIn1': _create_do_MV_1_AnIn1,
        'SPC_1_SPCSO6': _create_do_SPC_1_SPCSO6,
        'SPC_1_SPCSO5': _create_do_SPC_1_SPCSO5,
        'SPC_1_SPCSO4': _create_do_SPC_1_SPCSO4,
        'LPL_2_NamPlt': _create_do_LPL_2_NamPlt,
        'SPC_1_SPCSO2': _create_do_SPC_1_SPCSO2,
        'SPC_1_SPCSO1': _create_do_SPC_1_SPCSO1,
    }
    fn = _dispatcher.get(type_ref)
    if fn:
        return fn(name, parent)
    return _create_do_by_cdc(name, cdc, parent)


def build_ied_model() -> IedModel:
    ied = IedModel(name="simpleIO")

    ld1 = LogicalDevice(name="GenericIO", ldName="GenericIO")

    ln1_1 = LogicalNode(name="LLN0", parent=ld1)
    do_mod_1 = _create_do_by_typeref("Mod", "INC_1_Mod", "INC", ln1_1)
    ln1_1.add_data_object(do_mod_1)
    do_beh_2 = _create_do_by_typeref("Beh", "INS_1_Beh", "INS", ln1_1)
    ln1_1.add_data_object(do_beh_2)
    do_health_3 = _create_do_by_typeref("Health", "INS_1_Beh", "INS", ln1_1)
    ln1_1.add_data_object(do_health_3)
    do_namplt_4 = _create_do_by_typeref("NamPlt", "LPL_1_NamPlt", "LPL", ln1_1)
    ln1_1.add_data_object(do_namplt_4)
    do_setint1_5 = _create_do_by_typeref("SetInt1", "ISP", "INS", ln1_1)
    ln1_1.add_data_object(do_setint1_5)
    do_setint2_6 = _create_do_by_typeref("SetInt2", "ISP", "INS", ln1_1)
    ln1_1.add_data_object(do_setint2_6)
    do_setint3_7 = _create_do_by_typeref("SetInt3", "ISP", "INS", ln1_1)
    ln1_1.add_data_object(do_setint3_7)
    do_setint4_8 = _create_do_by_typeref("SetInt4", "ISP", "INS", ln1_1)
    ln1_1.add_data_object(do_setint4_8)
    do_setbool1_9 = _create_do_by_typeref("SetBool1", "SPG_1", "SPG", ln1_1)
    ln1_1.add_data_object(do_setbool1_9)
    do_setbool2_10 = _create_do_by_typeref("SetBool2", "SPG_1", "SPG", ln1_1)
    ln1_1.add_data_object(do_setbool2_10)
    do_setbool3_11 = _create_do_by_typeref("SetBool3", "SPG_1", "SPG", ln1_1)
    ln1_1.add_data_object(do_setbool3_11)
    do_setbool4_12 = _create_do_by_typeref("SetBool4", "SPG_1", "SPG", ln1_1)
    ln1_1.add_data_object(do_setbool4_12)
    do_int64_13 = _create_do_by_typeref("Int64", "INS_64", "INS", ln1_1)
    ln1_1.add_data_object(do_int64_13)
    do_setanval_14 = _create_do_by_typeref("SetAnVal", "ASG", "ASG", ln1_1)
    ln1_1.add_data_object(do_setanval_14)
    dataset_1_1_1 = DataSet(ln1_1, "GenericIO", "Events")
    data_entry_1_1_1_1 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO1.stVal", FunctionalConstraint.st)
    dataset_1_1_1.add_entry(data_entry_1_1_1_1)
    data_entry_1_1_1_2 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO2.stVal", FunctionalConstraint.st)
    dataset_1_1_1.add_entry(data_entry_1_1_1_2)
    data_entry_1_1_1_3 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO3.stVal", FunctionalConstraint.st)
    dataset_1_1_1.add_entry(data_entry_1_1_1_3)
    data_entry_1_1_1_4 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO4.stVal", FunctionalConstraint.st)
    dataset_1_1_1.add_entry(data_entry_1_1_1_4)
    ln1_1.add_data_set(dataset_1_1_1)
    dataset_1_1_2 = DataSet(ln1_1, "GenericIO", "EventsFCDO")
    data_entry_1_1_2_1 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO1", FunctionalConstraint.st)
    dataset_1_1_2.add_entry(data_entry_1_1_2_1)
    data_entry_1_1_2_2 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO2", FunctionalConstraint.st)
    dataset_1_1_2.add_entry(data_entry_1_1_2_2)
    data_entry_1_1_2_3 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO3", FunctionalConstraint.st)
    dataset_1_1_2.add_entry(data_entry_1_1_2_3)
    data_entry_1_1_2_4 = DataSetEntry("GenericIO", "GenericIO/GGIO1.SPCSO4", FunctionalConstraint.st)
    dataset_1_1_2.add_entry(data_entry_1_1_2_4)
    ln1_1.add_data_set(dataset_1_1_2)
    dataset_1_1_3 = DataSet(ln1_1, "GenericIO", "Booleans")
    data_entry_1_1_3_1 = DataSetEntry("GenericIO", "GenericIO/LLN0.SetBool1.setVal", FunctionalConstraint.sp)
    dataset_1_1_3.add_entry(data_entry_1_1_3_1)
    data_entry_1_1_3_2 = DataSetEntry("GenericIO", "GenericIO/LLN0.SetBool2.setVal", FunctionalConstraint.sp)
    dataset_1_1_3.add_entry(data_entry_1_1_3_2)
    data_entry_1_1_3_3 = DataSetEntry("GenericIO", "GenericIO/LLN0.SetBool3.setVal", FunctionalConstraint.sp)
    dataset_1_1_3.add_entry(data_entry_1_1_3_3)
    data_entry_1_1_3_4 = DataSetEntry("GenericIO", "GenericIO/LLN0.SetBool4.setVal", FunctionalConstraint.sp)
    dataset_1_1_3.add_entry(data_entry_1_1_3_4)
    ln1_1.add_data_set(dataset_1_1_3)
    dataset_1_1_4 = DataSet(ln1_1, "GenericIO", "Integers")
    data_entry_1_1_4_1 = DataSetEntry("GenericIO", "GenericIO/LLN01.SetInt1.setVal", FunctionalConstraint.sp)
    dataset_1_1_4.add_entry(data_entry_1_1_4_1)
    data_entry_1_1_4_2 = DataSetEntry("GenericIO", "GenericIO/LLN01.SetInt2.setVal", FunctionalConstraint.sp)
    dataset_1_1_4.add_entry(data_entry_1_1_4_2)
    data_entry_1_1_4_3 = DataSetEntry("GenericIO", "GenericIO/LLN01.SetInt3.setVal", FunctionalConstraint.sp)
    dataset_1_1_4.add_entry(data_entry_1_1_4_3)
    data_entry_1_1_4_4 = DataSetEntry("GenericIO", "GenericIO/LLN01.SetInt4.setVal", FunctionalConstraint.sp)
    dataset_1_1_4.add_entry(data_entry_1_1_4_4)
    ln1_1.add_data_set(dataset_1_1_4)
    rcb_1_1_1 = ReportControl(
        name="EventsRCB",
        buffered=False,
        dataset_name="Events",
        rpt_id="Events1",
        conf_rev=1,
        trg_ops={
            'dchg': False,
            'qchg': False,
            'dupd': False,
            'period': True,
            'gi': False
        },
        opt_flds={
            'seqNum': True,
            'timeStamp': True,
            'dataSet': True,
            'reasonCode': True,
            'dataRef': False,
            'entryID': True,
            'configRef': True,
            'bufOvfl': False
        },
        buffered_time=50,
        int_period=1000,
        indexed=True,
    )
    ln1_1.add_report_control(rcb_1_1_1)
    rcb_1_1_2 = ReportControl(
        name="BufferedRCB",
        buffered=True,
        dataset_name="Events",
        rpt_id="Events1",
        conf_rev=1,
        trg_ops={
            'dchg': False,
            'qchg': False,
            'dupd': False,
            'period': True,
            'gi': False
        },
        opt_flds={
            'seqNum': True,
            'timeStamp': True,
            'dataSet': True,
            'reasonCode': True,
            'dataRef': False,
            'entryID': True,
            'configRef': True,
            'bufOvfl': False
        },
        buffered_time=50,
        int_period=1000,
        indexed=True,
    )
    ln1_1.add_report_control(rcb_1_1_2)
    ld1.add_logical_node(ln1_1)
    ln1_2 = LogicalNode(name="LPHD1", parent=ld1)
    do_phynam_1 = _create_do_by_typeref("PhyNam", "DPL_1_PhyNam", "DPL", ln1_2)
    ln1_2.add_data_object(do_phynam_1)
    do_phyhealth_2 = _create_do_by_typeref("PhyHealth", "INS_1_Beh", "INS", ln1_2)
    ln1_2.add_data_object(do_phyhealth_2)
    do_proxy_3 = _create_do_by_typeref("Proxy", "SPS_1_Proxy", "SPS", ln1_2)
    ln1_2.add_data_object(do_proxy_3)
    ld1.add_logical_node(ln1_2)
    ln1_3 = LogicalNode(name="GGIO1", parent=ld1)
    do_mod_1 = _create_do_by_typeref("Mod", "INC_1_Mod", "INC", ln1_3)
    ln1_3.add_data_object(do_mod_1)
    do_beh_2 = _create_do_by_typeref("Beh", "INS_1_Beh", "INS", ln1_3)
    ln1_3.add_data_object(do_beh_2)
    do_health_3 = _create_do_by_typeref("Health", "INS_1_Beh", "INS", ln1_3)
    ln1_3.add_data_object(do_health_3)
    do_namplt_4 = _create_do_by_typeref("NamPlt", "LPL_2_NamPlt", "LPL", ln1_3)
    ln1_3.add_data_object(do_namplt_4)
    do_anin1_5 = _create_do_by_typeref("AnIn1", "MV_1_AnIn1", "MV", ln1_3)
    ln1_3.add_data_object(do_anin1_5)
    do_anin2_6 = _create_do_by_typeref("AnIn2", "MV_1_AnIn1", "MV", ln1_3)
    ln1_3.add_data_object(do_anin2_6)
    do_anin3_7 = _create_do_by_typeref("AnIn3", "MV_1_AnIn1", "MV", ln1_3)
    ln1_3.add_data_object(do_anin3_7)
    do_anin4_8 = _create_do_by_typeref("AnIn4", "MV_1_AnIn1", "MV", ln1_3)
    ln1_3.add_data_object(do_anin4_8)
    do_spcso1_9 = _create_do_by_typeref("SPCSO1", "SPC_1_SPCSO1", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso1_9)
    do_spcso2_10 = _create_do_by_typeref("SPCSO2", "SPC_1_SPCSO2", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso2_10)
    do_spcso3_11 = _create_do_by_typeref("SPCSO3", "SPC_1_SPCSO3", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso3_11)
    do_spcso4_12 = _create_do_by_typeref("SPCSO4", "SPC_1_SPCSO4", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso4_12)
    do_spcso5_13 = _create_do_by_typeref("SPCSO5", "SPC_1_SPCSO5", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso5_13)
    do_spcso6_14 = _create_do_by_typeref("SPCSO6", "SPC_1_SPCSO6", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso6_14)
    do_spcso7_15 = _create_do_by_typeref("SPCSO7", "SPC_1_SPCSO7", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso7_15)
    do_spcso8_16 = _create_do_by_typeref("SPCSO8", "SPC_1_SPCSO8", "SPC", ln1_3)
    ln1_3.add_data_object(do_spcso8_16)
    do_ind1_17 = _create_do_by_typeref("Ind1", "SPS_1_Proxy", "SPS", ln1_3)
    ln1_3.add_data_object(do_ind1_17)
    do_ind2_18 = _create_do_by_typeref("Ind2", "SPS_1_Proxy", "SPS", ln1_3)
    ln1_3.add_data_object(do_ind2_18)
    do_ind3_19 = _create_do_by_typeref("Ind3", "SPS_1_Proxy", "SPS", ln1_3)
    ln1_3.add_data_object(do_ind3_19)
    do_ind4_20 = _create_do_by_typeref("Ind4", "SPS_1_Proxy", "SPS", ln1_3)
    ln1_3.add_data_object(do_ind4_20)
    do_schdabstm_21 = _create_do_by_typeref("SchdAbsTm", "SCA_1_SchdAbsTm", "SCA", ln1_3)
    ln1_3.add_data_object(do_schdabstm_21)
    ld1.add_logical_node(ln1_3)
    ln1_4 = LogicalNode(name="MHAI1", parent=ld1)
    do_ha_1 = _create_do_by_typeref("HA", "HWYE_1_HA", "HWYE", ln1_4)
    ln1_4.add_data_object(do_ha_1)
    ld1.add_logical_node(ln1_4)

    ied.add_logical_device(ld1)

    return ied


ied = build_ied_model()