"""Auto-generated model script from SCL DataTypeTemplates and IED section.
Source file: rti_v1.0.scd
Generated by: SCL Model Factory"""

from __future__ import annotations

from dataclasses import asdict
from typing import Optional

from ws61850.iec61850.data_model import *
from ws61850.protocol.types import OptFlds

BTYPE_TO_DA_ENUM_NAME = {"BOOLEAN":"boolean","INT8":"int8","INT16":"int16","INT24":"int24","INT32":"int32","INT64":"int64","INT8U":"int8u","INT16U":"int16u","INT24U":"int24u","INT32U":"int32u","FLOAT32":"float32","FLOAT64":"float64","Enum":"enumerated","Quality":"quality","Timestamp":"timeStamp","Check":"check","Struct":"structure","VisString64":"visString64","VisString129":"visString129","VisString255":"visString255","Octet64":"octetString","OctetString":"octetString","ObjRef":"visString255","Dbpos":"enumerated","Tcmd":"enumerated","Unicode255":"visString255","PhyComAddr":"octetString"}
FC_TO_ENUM_NAME = {"ST":"st","MX":"mx","SP":"sp","SV":"sv","CF":"cf","DC":"dc","SG":"sg","SE":"se","SR":"sr","OR":"or_","BL":"bl","EX":"ex","LG":"lg","CO":"co"}

def _create_da_Originator(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_orcat_1 = DataAttribute('orCat', DataAttributeType.enumerated, fc, None, da)
    da.add_data_attribute(_bda_orcat_1)
    _bda_orident_2 = DataAttribute('orIdent', DataAttributeType.octetString, fc, None, da)
    da.add_data_attribute(_bda_orident_2)
    return da

def _create_da_OperINT32(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_ctlval_1 = DataAttribute('ctlVal', DataAttributeType.int32, fc, None, da)
    da.add_data_attribute(_bda_ctlval_1)
    _bda_origin_2 = _create_da_Originator('origin', fc, da)
    da.add_data_attribute(_bda_origin_2)
    _bda_ctlnum_3 = DataAttribute('ctlNum', DataAttributeType.int8u, fc, None, da)
    da.add_data_attribute(_bda_ctlnum_3)
    _bda_t_4 = DataAttribute('T', DataAttributeType.timeStamp, fc, None, da)
    da.add_data_attribute(_bda_t_4)
    _bda_test_5 = DataAttribute('Test', DataAttributeType.boolean, fc, None, da)
    da.add_data_attribute(_bda_test_5)
    _bda_check_6 = DataAttribute('Check', DataAttributeType.check, fc, None, da)
    da.add_data_attribute(_bda_check_6)
    return da

def _create_da_Unit(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_siunit_1 = DataAttribute('SIUnit', DataAttributeType.enumerated, fc, None, da)
    da.add_data_attribute(_bda_siunit_1)
    _bda_multiplier_2 = DataAttribute('multiplier', DataAttributeType.enumerated, fc, None, da)
    da.add_data_attribute(_bda_multiplier_2)
    return da

def _create_da_OperAnalog(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_ctlval_1 = _create_da_AnalogueValue('ctlVal', fc, da)
    da.add_data_attribute(_bda_ctlval_1)
    _bda_origin_2 = _create_da_Originator('origin', fc, da)
    da.add_data_attribute(_bda_origin_2)
    _bda_ctlnum_3 = DataAttribute('ctlNum', DataAttributeType.int8u, fc, None, da)
    da.add_data_attribute(_bda_ctlnum_3)
    _bda_t_4 = DataAttribute('T', DataAttributeType.timeStamp, fc, None, da)
    da.add_data_attribute(_bda_t_4)
    _bda_test_5 = DataAttribute('Test', DataAttributeType.boolean, fc, None, da)
    da.add_data_attribute(_bda_test_5)
    _bda_check_6 = DataAttribute('Check', DataAttributeType.check, fc, None, da)
    da.add_data_attribute(_bda_check_6)
    return da

def _create_da_AnalogueValue(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_f_1 = DataAttribute('f', DataAttributeType.float32, fc, None, da)
    da.add_data_attribute(_bda_f_1)
    return da

def _create_da_Vector(name, fc, parent):
    da = DataAttribute(name, DataAttributeType.structure, fc, [], parent)
    _bda_mag_1 = _create_da_AnalogueValue('mag', fc, da)
    da.add_data_attribute(_bda_mag_1)
    return da

def _create_do_ING(name, parent):
    do = DataObject(name, "ing", parent=parent)
    _da_setval_1 = DataAttribute('setVal', DataAttributeType.int32, FunctionalConstraint.sp, None, do)
    do.add_do_or_da(_da_setval_1)
    _da_units_2 = _create_da_Unit('units', FunctionalConstraint.cf, do)
    do.add_do_or_da(_da_units_2)
    _da_datans_3 = DataAttribute('dataNs', DataAttributeType.visString255, FunctionalConstraint.ex, None, do)
    do.add_do_or_da(_da_datans_3)
    return do

def _create_do_ASG(name, parent):
    do = DataObject(name, "asg", parent=parent)
    _da_setmag_1 = _create_da_AnalogueValue('setMag', FunctionalConstraint.sp, do)
    do.add_do_or_da(_da_setmag_1)
    _da_units_2 = _create_da_Unit('units', FunctionalConstraint.cf, do)
    do.add_do_or_da(_da_units_2)
    _da_datans_3 = DataAttribute('dataNs', DataAttributeType.visString255, FunctionalConstraint.ex, None, do)
    do.add_do_or_da(_da_datans_3)
    return do

def _create_do_DERStateKind_ENS(name, parent):
    do = DataObject(name, "ens", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_ens_HealthKind(name, parent):
    do = DataObject(name, "ens", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_DPL(name, parent):
    do = DataObject(name, "dpl", parent=parent)
    _da_vendor_1 = DataAttribute('vendor', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_vendor_1)
    _da_hwrev_2 = DataAttribute('hwRev', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_hwrev_2)
    _da_swrev_3 = DataAttribute('swRev', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_swrev_3)
    _da_sernum_4 = DataAttribute('serNum', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_sernum_4)
    _da_model_5 = DataAttribute('model', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_model_5)
    _da_location_6 = DataAttribute('location', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_location_6)
    return do

def _create_do_SPS(name, parent):
    do = DataObject(name, "sps", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.boolean, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_ens_BehaviourModeKind(name, parent):
    do = DataObject(name, "ens", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_t_3)
    return do

def _create_do_enc_BehaviourModeKind(name, parent):
    do = DataObject(name, "enc", parent=parent)
    _da_stval_1 = DataAttribute('stVal', DataAttributeType.enumerated, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_stval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_t_3)
    _da_ctlmodel_4 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 'status-only', do)
    do.add_do_or_da(_da_ctlmodel_4)
    return do

def _create_do_LPL(name, parent):
    do = DataObject(name, "lpl", parent=parent)
    _da_vendor_1 = DataAttribute('vendor', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_vendor_1)
    _da_swrev_2 = DataAttribute('swRev', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_swrev_2)
    _da_configrev_3 = DataAttribute('configRev', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_configrev_3)
    _da_ldns_4 = DataAttribute('ldNs', DataAttributeType.visString255, FunctionalConstraint.ex, 'IEC 61850-7-4:2007A', do)
    do.add_do_or_da(_da_ldns_4)
    _da_lnns_5 = DataAttribute('lnNs', DataAttributeType.visString255, FunctionalConstraint.ex, 'IEC 61850-7-4:2007A', do)
    do.add_do_or_da(_da_lnns_5)
    return do

def _create_do_LPL_420(name, parent):
    do = DataObject(name, "lpl", parent=parent)
    _da_vendor_1 = DataAttribute('vendor', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_vendor_1)
    _da_swrev_2 = DataAttribute('swRev', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_swrev_2)
    _da_configrev_3 = DataAttribute('configRev', DataAttributeType.visString255, FunctionalConstraint.dc, None, do)
    do.add_do_or_da(_da_configrev_3)
    _da_lnns_4 = DataAttribute('lnNs', DataAttributeType.visString255, FunctionalConstraint.ex, 'IEC 61850-7-420:2019', do)
    do.add_do_or_da(_da_lnns_4)
    return do

def _create_do_MV(name, parent):
    do = DataObject(name, "mv", parent=parent)
    _da_mag_1 = _create_da_AnalogueValue('mag', FunctionalConstraint.mx, do)
    do.add_do_or_da(_da_mag_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.mx, None, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.mx, None, do)
    do.add_do_or_da(_da_t_3)
    _da_units_4 = _create_da_Unit('units', FunctionalConstraint.cf, do)
    do.add_do_or_da(_da_units_4)
    return do

def _create_do_CMV(name, parent):
    do = DataObject(name, "cmv", parent=parent)
    _da_cval_1 = _create_da_Vector('cVal', FunctionalConstraint.mx, do)
    do.add_do_or_da(_da_cval_1)
    _da_q_2 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.mx, None, do)
    do.add_do_or_da(_da_q_2)
    _da_t_3 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.mx, None, do)
    do.add_do_or_da(_da_t_3)
    _da_units_4 = _create_da_Unit('units', FunctionalConstraint.cf, do)
    do.add_do_or_da(_da_units_4)
    return do

def _create_do_WYE(name, parent):
    do = DataObject(name, "wye", parent=parent)
    _sdo_phsa_1 = _create_do_by_typeref('phsA', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsa_1)
    _sdo_phsb_2 = _create_do_by_typeref('phsB', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsb_2)
    _sdo_phsc_3 = _create_do_by_typeref('phsC', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsc_3)
    return do

def _create_do_DEL(name, parent):
    do = DataObject(name, "del", parent=parent)
    _sdo_phsab_1 = _create_do_by_typeref('phsAB', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsab_1)
    _sdo_phsbc_2 = _create_do_by_typeref('phsBC', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsbc_2)
    _sdo_phsca_3 = _create_do_by_typeref('phsCA', 'CMV', 'CMV', do)
    do.add_do_or_da(_sdo_phsca_3)
    return do

def _create_do_APC(name, parent):
    do = DataObject(name, "apc", parent=parent)
    _da_oper_1 = _create_da_OperAnalog('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_1)
    _da_mxval_2 = _create_da_AnalogueValue('mxVal', FunctionalConstraint.mx, do)
    do.add_do_or_da(_da_mxval_2)
    _da_q_3 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.mx, None, do)
    do.add_do_or_da(_da_q_3)
    _da_t_4 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.mx, None, do)
    do.add_do_or_da(_da_t_4)
    _da_units_5 = _create_da_Unit('units', FunctionalConstraint.cf, do)
    do.add_do_or_da(_da_units_5)
    _da_ctlmodel_6 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 'direct-with-normal-security', do)
    do.add_do_or_da(_da_ctlmodel_6)
    return do

def _create_do_INC(name, parent):
    do = DataObject(name, "inc", parent=parent)
    _da_oper_1 = _create_da_OperINT32('Oper', FunctionalConstraint.co, do)
    do.add_do_or_da(_da_oper_1)
    _da_stval_2 = DataAttribute('stVal', DataAttributeType.int32, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_stval_2)
    _da_q_3 = DataAttribute('q', DataAttributeType.quality, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_q_3)
    _da_t_4 = DataAttribute('t', DataAttributeType.timeStamp, FunctionalConstraint.st, None, do)
    do.add_do_or_da(_da_t_4)
    _da_ctlmodel_5 = DataAttribute('ctlModel', DataAttributeType.enumerated, FunctionalConstraint.cf, 'direct-with-normal-security', do)
    do.add_do_or_da(_da_ctlmodel_5)
    _da_datans_6 = DataAttribute('dataNs', DataAttributeType.visString255, FunctionalConstraint.ex, 'NBNL_RTI_version1', do)
    do.add_do_or_da(_da_datans_6)
    return do

def _create_do_by_cdc(name: str, cdc: Optional[str], parent):
    cdc_norm = (cdc or '').lower()
    return DataObject(name, cdc_norm, parent=parent)

def _create_do_by_typeref(name: str, type_ref, cdc, parent):
    _dispatcher = {
        'ING': _create_do_ING,
        'ASG': _create_do_ASG,
        'DERStateKind_ENS': _create_do_DERStateKind_ENS,
        'ens_HealthKind': _create_do_ens_HealthKind,
        'DPL': _create_do_DPL,
        'SPS': _create_do_SPS,
        'ens_BehaviourModeKind': _create_do_ens_BehaviourModeKind,
        'enc_BehaviourModeKind': _create_do_enc_BehaviourModeKind,
        'LPL': _create_do_LPL,
        'LPL_420': _create_do_LPL_420,
        'MV': _create_do_MV,
        'CMV': _create_do_CMV,
        'WYE': _create_do_WYE,
        'DEL': _create_do_DEL,
        'APC': _create_do_APC,
        'INC': _create_do_INC,
    }
    fn = _dispatcher.get(type_ref)
    if fn:
        return fn(name, parent)
    return _create_do_by_cdc(name, cdc, parent)


def build_ied_model() -> IedModel:
    ied = IedModel(name="IED_2")

    ld1 = LogicalDevice(name="LD0", ldName="RTIserver1_0_0")

    ln1_1 = LogicalNode(name="LLN0", parent=ld1)
    do_mod_1 = _create_do_by_typeref("Mod", "enc_BehaviourModeKind", "ENC", ln1_1)
    ln1_1.add_data_object(do_mod_1)
    do_namplt_2 = _create_do_by_typeref("NamPlt", "LPL", "LPL", ln1_1)
    ln1_1.add_data_object(do_namplt_2)
    do_beh_3 = _create_do_by_typeref("Beh", "ens_BehaviourModeKind", "ENS", ln1_1)
    ln1_1.add_data_object(do_beh_3)
    do_health_4 = _create_do_by_typeref("Health", "ens_HealthKind", "ENS", ln1_1)
    ln1_1.add_data_object(do_health_4)
    ld1.add_logical_node(ln1_1)
    ln1_2 = LogicalNode(name="LPHD1", parent=ld1)
    do_phynam_1 = _create_do_by_typeref("PhyNam", "DPL", "DPL", ln1_2)
    ln1_2.add_data_object(do_phynam_1)
    do_phyhealth_2 = _create_do_by_typeref("PhyHealth", "ens_HealthKind", "ENS", ln1_2)
    ln1_2.add_data_object(do_phyhealth_2)
    do_proxy_3 = _create_do_by_typeref("Proxy", "SPS", "SPS", ln1_2)
    ln1_2.add_data_object(do_proxy_3)
    do_pwrup_4 = _create_do_by_typeref("PwrUp", "SPS", "SPS", ln1_2)
    ln1_2.add_data_object(do_pwrup_4)
    ld1.add_logical_node(ln1_2)
    ln1_3 = LogicalNode(name="DWMX1", parent=ld1)
    do_namplt_1 = _create_do_by_typeref("NamPlt", "LPL_420", "LPL", ln1_3)
    ln1_3.add_data_object(do_namplt_1)
    do_beh_2 = _create_do_by_typeref("Beh", "ens_BehaviourModeKind", "ENS", ln1_3)
    ln1_3.add_data_object(do_beh_2)
    do_wmaxsptpct_3 = _create_do_by_typeref("WMaxSptPct", "APC", "APC", ln1_3)
    ln1_3.add_data_object(do_wmaxsptpct_3)
    do_wmaxspt_4 = _create_do_by_typeref("WMaxSpt", "APC", "APC", ln1_3)
    ln1_3.add_data_object(do_wmaxspt_4)
    do_wmaxsetpct_5 = _create_do_by_typeref("WMaxSetPct", "ASG", "ASG", ln1_3)
    ln1_3.add_data_object(do_wmaxsetpct_5)
    do_wmaxset_6 = _create_do_by_typeref("WMaxSet", "ASG", "ASG", ln1_3)
    ln1_3.add_data_object(do_wmaxset_6)
    do_wmaxfto_7 = _create_do_by_typeref("WMaxFto", "ING", "ING", ln1_3)
    ln1_3.add_data_object(do_wmaxfto_7)
    do_sptreas_8 = _create_do_by_typeref("SptReas", "INC", "INC", ln1_3)
    ln1_3.add_data_object(do_sptreas_8)
    ld1.add_logical_node(ln1_3)
    ln1_4 = LogicalNode(name="DGEN1", parent=ld1)
    do_namplt_1 = _create_do_by_typeref("NamPlt", "LPL_420", "LPL", ln1_4)
    ln1_4.add_data_object(do_namplt_1)
    do_beh_2 = _create_do_by_typeref("Beh", "ens_BehaviourModeKind", "ENS", ln1_4)
    ln1_4.add_data_object(do_beh_2)
    do_deropst_3 = _create_do_by_typeref("DEROpSt", "DERStateKind_ENS", "ENS", ln1_4)
    ln1_4.add_data_object(do_deropst_3)
    ld1.add_logical_node(ln1_4)
    ln1_5 = LogicalNode(name="MMXU1", parent=ld1)
    do_beh_1 = _create_do_by_typeref("Beh", "ens_BehaviourModeKind", "ENS", ln1_5)
    ln1_5.add_data_object(do_beh_1)
    do_totw_2 = _create_do_by_typeref("TotW", "MV", "MV", ln1_5)
    ln1_5.add_data_object(do_totw_2)
    do_totvar_3 = _create_do_by_typeref("TotVAr", "MV", "MV", ln1_5)
    ln1_5.add_data_object(do_totvar_3)
    do_phv_4 = _create_do_by_typeref("PhV", "WYE", "WYE", ln1_5)
    ln1_5.add_data_object(do_phv_4)
    do_ppv_5 = _create_do_by_typeref("PPV", "DEL", "DEL", ln1_5)
    ln1_5.add_data_object(do_ppv_5)
    do_a_6 = _create_do_by_typeref("A", "WYE", "WYE", ln1_5)
    ln1_5.add_data_object(do_a_6)
    do_avwphs_7 = _create_do_by_typeref("AvWPhs", "MV", "MV", ln1_5)
    ln1_5.add_data_object(do_avwphs_7)
    do_maxwphs_8 = _create_do_by_typeref("MaxWPhs", "MV", "MV", ln1_5)
    ln1_5.add_data_object(do_maxwphs_8)
    do_minwphs_9 = _create_do_by_typeref("MinWPhs", "MV", "MV", ln1_5)
    ln1_5.add_data_object(do_minwphs_9)
    ld1.add_logical_node(ln1_5)

    ied.add_logical_device(ld1)

    return ied


ied = build_ied_model()